version: "3.9"
services:
  mysql:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: gdscturk
      MYSQL_DATABASE: gdscturk
      MYSQL_USER: gdscturk
      MYSQL_PASSWORD: gdscturk
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
networks:
  container_network:
    driver: bridge
